site_name: Card Game App 
site_url: https://tomoishi0515-alt.github.io/streamlit-practice/
theme:
  name: material
nav:
  - Home: index.md
  - About: about.md
  - High and Low Game: howtouse/high_and_low.md
  - Hit and Blow Game: howtouse/hit_and_blow.md
repo_url: https://github.com/tomoishi0515-alt/streamlit-practice
extra:
  version:
    provider: mike